services:
  web-app:
    build: .
    container_name: spring-app-compose
    ports:
      - "9090:9090"
    networks:
      - app-network
    environment:
      - SPRING_PROFILES_ACTIVE=dev
    depends_on:
      - database

  database:
    image: postgres:16-alpine
    container_name: postgres-db-compose
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: enginedb
    ports:
      - "5432:5432"
    networks:
      - app-network
    volumes:
      - db-data:/var/lib/postgresql/data

networks:
  app-network:
    driver: bridge

volumes:
  db-data:
    name: "spring-app-database"